name = "pnit-api"
main = "src/index.ts"
compatibility_date = "2026-01-20"
routes = [
  { pattern = "api.pnit.infinity.dev.br", zone_name = "infinity.dev.br", custom_domain = true }
]

[triggers]
crons = ["0 2 * * *"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pnit-assets"

# deploy trigger

# deploy trigger
