name = "pnit-api"
main = "src/index.ts"
compatibility_date = "2026-01-20"

[triggers]
crons = ["0 2 * * *"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pnit-assets"

# deploy trigger

# deploy trigger
